config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories, except: :show
    resources :sub_categories, except: :show
  end

  get '/:category_slug/:sub_category_slug/', to: 'sub_categories#show', as: 'sub_category'

  root 'admin/categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, dependent: :destroy

  validates :name, :slug, presence: true
end

app/models/checkbox.rb
class Checkbox < Field
end

app/models/field.rb
class Field < ActiveRecord::Base
  TYPES = %w(checkbox select text textarea)

  belongs_to :sub_category
  has_many :options, as: :optionable

  accepts_nested_attributes_for :options, allow_destroy: true, reject_if: :without_option?

  validates :order, :title, :type, presence: true

  scope :by_order_value, -> { order(:order) }

  private

  def without_option?
    type == 'Text' || type == 'Textarea'
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :optionable, polymorphic: true

  validates :title, :value, presence: true
end

app/models/select.rb
class Select < Field
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :fields, dependent: :destroy

  accepts_nested_attributes_for :fields, allow_destroy: true

  scope :categories_by_slug, -> (slug) { joins(:category).where(categories: { slug: slug }) }

  validates :name, :slug, :category, presence: true
end

app/models/text.rb
class Text < Field
end

app/models/textarea.rb
class Textarea < Field
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :find_category, only: [:edit, :update, :destroy]

  layout 'admin'

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Categoria criada com sucesso!'
      redirect_to admin_categories_path
    else
      flash[:danger] = 'Erro ao criar categoria!'
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Categoria atualizada com sucesso!'
      redirect_to admin_categories_path
    else
      flash[:danger] = 'Erro ao atualizar categoria!'
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = 'Categoria apagada com sucesso!'
    else
      flash[:danger] = 'Erro ao apagar categoria!'
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin/sub_categories_controller.rb
class Admin::SubCategoriesController < ApplicationController
  before_filter :find_sub_category, only: [:edit, :update, :destroy]

  layout "admin"

  def index
    @sub_categories = SubCategory.all
  end

  def new
    @sub_category = SubCategory.new
  end

  def create
    @sub_category = SubCategory.new(sub_category_params)
    if @sub_category.save
      flash[:success] = 'Subcategoria criada com sucesso!'
      redirect_to admin_sub_categories_path
    else
      flash[:danger] = 'Erro ao criar subcategoria!'
      render :new
    end
  end

  def edit
  end

  def update
    if @sub_category.update_attributes(sub_category_params)
      flash[:success] = 'Subcategoria atualizada com sucesso!'
      redirect_to admin_sub_categories_path
    else
      flash[:danger] = 'Erro ao atualizar subcategoria!'
      render :edit
    end
  end

  def destroy
    if @sub_category.destroy
      flash[:success] = 'Subcategoria apagada com sucesso!'
    else
      flash[:danger] = 'Erro ao apagar subcategoria!'
    end
    redirect_to admin_sub_categories_path
  end

  private

  def sub_category_params
    params.require(:sub_category).permit(:category_id, :name, :slug, fields_attributes: field_params)
  end

  def field_params
    [:id, :order, :title, :type, :_destroy, options_attributes: options_params]
  end

  def options_params
    [:id, :title, :value, :_destroy]
  end

  def find_sub_category
    @sub_category = SubCategory.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def show
    @sub_category = SubCategory.where(slug: params[:sub_category_slug]).categories_by_slug(params[:category_slug]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def categories_for_select
    Category.pluck(:name, :id)
  end

  def field_types_for_select
    Field::TYPES.map { |t| [t, t.capitalize] }
  end

  def fields_amount_for_select(id)
    size = Field.where(sub_category_id: id).size
    1..size + 1
  end

  def link_to_remove_associations(name, f, association)
    f.hidden_field(:_destroy) + link_to(name, '#', onclick: "remove_associations(this, \"#{association}\")")
  end

  def link_to_add_associations(name, f, association)
    return unless f.object.respond_to?(association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render("#{association}_form", f: builder)
    end
    link_to(name, '#', onclick: "add_associations(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def checkbox_builder(field)
    response = field.options.inject('') do |list, option|
      list += "<div class='checkbox'><label>#{check_box_tag(option.title, option.value)} #{option.title}</label></div>"
    end
    response.html_safe
  end

  def text_builder(field)
    text_field_tag field.title, nil, class: "form-control"
  end

  def select_builder(field)
    options = field.options.pluck(:title, :value)
    select_tag(field.title, options_for_select(options), {class: "form-control"})
  end

  def textarea_builder(field)
    text_area_tag(field.title, nil, class: "form-control", rows: 4)
  end
end

app/helpers/flash_message_helper.rb
module FlashMessageHelper
  def flash_message
    messages = ""
    [:success, :danger].each do |type|
      if flash[type]
        messages += "<div class=\"alert alert-#{type}\"><strong>#{flash[type]}.</div>"
      end
    end
    messages.html_safe
  end
end

app/views/admin/categories/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Nome" %>
</div>

<div class="form-group">
  <%= f.label :slug %>
  <%= f.text_field :slug, class: "form-control", placeholder: "Slug" %>
</div>
<hr>
<%= f.submit 'Salvar', class: "btn btn-primary btn-block"%>

app/views/admin/categories/edit.html.erb
<div class="col-md-12">
  <h2>
    Editar Categoria
    <div class="pull-right">
      <%= link_to "Back", admin_categories_url, class: "btn btn-default btn-link" %>
    </div>
  </h2>
  <hr>
  <%= form_for(@category, url: admin_category_path(@category), method: :put) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="col-md-12">
  <h2>Listando Categorias</h2>
  <hr>
  <div class="table-responsive">
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <th>Nome</th>
        <th>Slug</th>
        <th colspan="2">Ações</th>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= category.slug %></td>
            <td>
              <%= link_to 'Editar', edit_admin_category_path(category) %>
              <%= link_to 'Apagar', admin_category_path(category), method: :delete, data: { confirm: 'Deseja realmente apagar esta categoria?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <hr>
  <%= link_to 'Nova Categoria', new_admin_category_path, class: "btn btn-block btn-primary" %>
</div>

app/views/admin/categories/new.html.erb
<div class="col-md-12">
  <h2>
    Nova Categoria
    <div class="pull-right">
      <%= link_to "Back", admin_categories_url, class: "btn btn-default btn-link" %>
    </div>
  </h2>
  <hr>
  <%= form_for(@category, url: admin_categories_path, method: :post) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
  <% end %>
</div>

app/views/admin/sub_categories/_fields_form.html.erb
<div class="fields">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <%= f.object.title || "Novo Campo" %>
    </div>
    <div class="panel-body">
      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :order %>
            <%= f.select :order, options_for_select(fields_amount_for_select(f.object.sub_category), f.object.order), {}, { class: "form-control" } %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :type %>
            <%= f.select :type, options_for_select(field_types_for_select, f.object.type), {}, { class: "form-control", onchange: 'show_or_hide_options(this);' } %>
          </div>
        </div>
      </div>

      <div class="options-box">
        <hr>
          <h4>Opções</h4>
        <hr>
        <%= f.fields_for :options do |of| %>
          <%= render partial: 'options_form', locals: { f: of } %>
        <% end %>

        <hr>
        <p><%= link_to_add_associations "Adicionar opções", f, :options %></p>
      </div>
    </div>

    <div class="panel-footer text-right">
      <%= link_to_remove_associations "Remover campo", f, :fields %>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/admin/sub_categories/_form.html.erb
<h4>Informações da Sub Categoria</h4>
<hr>

<div class="col-md-4">
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Nome" %>
  </div>
</div>

<div class="col-md-4">
  <div class="form-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, class: "form-control", placeholder: "Slug" %>
  </div>
</div>

<div class="col-md-4">
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, options_for_select(categories_for_select, f.object.category_id), {}, { class: "form-control" }%>
  </div>
</div>

<div class="clearfix"></div>

<% unless f.object.fields.blank? %>
  <hr>
  <h4>Campos da Sub Categoria</h4>
  <hr>
<% end %>

<%= f.fields_for :fields do |ff| %>
  <%= render partial: 'fields_form', locals: { f: ff } %>
<% end %>

<hr>
<p>
  <%= link_to_add_associations "Adicionar campo", f, :fields %>
</p>
<hr>
<%= f.submit 'Salvar', class: "btn btn-primary btn-block"%>

app/views/admin/sub_categories/_options_form.html.erb
<div class="options">
  <div class="panel panel-info">
    <div class="panel-heading">
      <%= f.object.title.present? ? f.object.title : "Nova Opção" %>
    </div>
    <div class="panel-body">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :value %>
          <%= f.text_field :value, class: "form-control" %>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
    <div class="panel-footer text-right">
      <%= link_to_remove_associations "Remover opção", f, :options %>
    </div>
  </div>
</div>

app/views/admin/sub_categories/edit.html.erb
<div class="col-md-12">
  <h2>
    Editar Sub Categoria
    <div class="pull-right">
      <%= link_to "Back", admin_sub_categories_url, class: "btn btn-default btn-link" %>
    </div>
  </h2>
  <hr>
  <%= form_for(@sub_category, url: admin_sub_category_path(@sub_category), method: :put) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
  <% end %>
</div>

app/views/admin/sub_categories/index.html.erb
<div class="col-md-12">
  <h2>Listando Sub Categorias</h2>
  <hr>
  <div class="table-responsive">
    <table class="table table-condensed table-striped table-hover">
      <thead>
        <th>Nome</th>
        <th>Slug</th>
        <th>Categoria</th>
        <th>Quantidade de campos</th>
        <th colspan="3">Ações</th>
      </thead>
      <tbody>
        <% @sub_categories.each do |sub_category| %>
          <tr>
            <td><%= sub_category.name %></td>
            <td><%= sub_category.slug %></td>
            <td><%= sub_category.category.name %></td>
            <td><%= sub_category.fields.size %></td>
            <td>
              <%= link_to 'Visualizar formulário', sub_category_path(category_slug: sub_category.category.slug, sub_category_slug: sub_category.slug) %>
              <%= link_to 'Editar', edit_admin_sub_category_path(sub_category) %>
              <%= link_to 'Apagar', admin_sub_category_path(sub_category), method: :delete, data: { confirm: 'Deseja realmente apagar esta subcategoria?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <hr>
  <%= link_to 'Nova Subcategoria', new_admin_sub_category_path, class: "btn btn-block btn-primary" %>
</div>

app/views/admin/sub_categories/new.html.erb
<div class="col-md-12">
  <h2>
    Nova Sub Categoria
    <div class="pull-right">
      <%= link_to "Back", admin_sub_categories_url, class: "btn btn-default btn-link" %>
    </div>
  </h2>
  <hr>
  <%= form_for(@sub_category, url: admin_sub_categories_path, method: :post) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div id="admin">
      <%= render "parts/admin/header" %>
      <div class="wrapper">
        <div class="container">
          <div class="row">
            <%= flash_message %>
            <%= yield %>
          </div>
        </div>
      </div
      <%= render "parts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render "parts/header" %>
    <%= yield %>
    <%= render "parts/footer" %>
  </body>
</html>

app/views/parts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <p>FORM - All rights reserved © 2016</p>
      <span>mfbmina@gmail.com</span>
    </div>
  </div>
</footer>

app/views/parts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#", class: "navbar-brand" do %>
          <img src="https://www.getninjas.com.br/assets/home/logo-3fd47ebb30bbd287141c06bf2eb812c8b7b0d03fc982cbb667a14dc7e97a7f05.png" alt="Getninjas">
          <span>GetNinjas</span>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
        </ul>
      </div><!-- /.navbar-collapse -->
    
      <br>
      <ul class="nav nav-pills" id="sub_menu">
        <% Category.select{|x| x.sub_categories.count > 0}.each do |category| %>
          <li role="presentation" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= category.name %>
            </a>
            <ul class="dropdown-menu">
              <% category.sub_categories.each do |sub_category| %>
                <li>
                  <%= link_to sub_category.name, sub_category_url(sub_category.category.slug, sub_category.slug) %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div><!-- /.container -->
</nav>

app/views/parts/admin/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#", class: "navbar-brand" do %>
          <img src="https://www.getninjas.com.br/assets/home/logo-3fd47ebb30bbd287141c06bf2eb812c8b7b0d03fc982cbb667a14dc7e97a7f05.png" alt="Getninjas">
          <span>GetNinjas</span>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= link_to "CATEGORIAS", admin_categories_url, class: "btn-topbar navbar-btn green" %>
          <%= link_to "SUB CATEGORIAS", admin_sub_categories_url, class: "btn-topbar navbar-btn" %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container -->
</nav>

app/views/sub_categories/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <ol class="breadcrumb">
        <li><a href="#">GetNinjas</a></li>
        <span>»</span>
        <li class="active"><%= @sub_category.category.name %></li>
        <span>»</span>
        <li class="active"><%= @sub_category.name %></li>
      </ol>
      <h1>A maneira mais fácil de encontrar <strong>Profissionais em <%= @sub_category.name %></strong></h1>
      <h2>Preencha os dados abaixo para te apresentarmos a localização e os telefones de profissionais na sua região</h2>
      <div class="col-md-10 col-md-offset-1">
        <div class="col-md-4">
          <div class="step-box">
            <img src="https://www.getninjas.com.br/assets/ab-test/categories/chat-421cb9441bb5ee9794a814b5125adbbec9e47f770b38d1206e01e4b706474483.png">
            <br>
            <span class="steps__description"><b>1.</b> Diga qual é o serviço que você precisa</span>
          </div>
        </div>
        <div class="col-md-4">
          <div class="step-box">
            <img src="https://www.getninjas.com.br/assets/ab-test/categories/search-ccf3527a797518d19a094c4e6225d3905c3ac327b56254bee92418ce00e1da06.png">
            <br>
            <span class="steps__description"><b>2.</b> Vamos procurar os 5 melhores profissionais para você</span>
          </div>
        </div>
        <div class="col-md-4">
          <div class="step-box">
            <img src="https://www.getninjas.com.br/assets/ab-test/categories/like-a1e34bc09aa37c6fe6dd1c1dc6afa1f6768e516653331c9671a87636e5b58ced.png">
            <br>
            <span class="steps__description"><b>3.</b>  Escolha o que melhor atende suas necessidades</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper no-margin-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="col-sm-6 col-sm-offset-3">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= form_tag '#' do %>
                <% @sub_category.fields.by_order_value.each do |field| %>
                  <div class="form-group">
                    <%= label_tag field.title %>
                    <%= send("#{field.type.downcase}_builder", field) %>
                  </div>
                <% end %>

                <%= submit_tag 'Continuar', class: "btn btn-block btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>